version: '3'
services:
  jenkins:
    container_name: jenkins_con_docker_1
    build: .
    ports: 
      - "8082:8080"
    volumes:
      - $PWD/jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock